# //--------------------------------------------

features_CARL_singlePoint_tZq = []
features_CARL_singlePoint_tZq.append("recoZ_Pt")
features_CARL_singlePoint_tZq.append("recoZ_Eta")
features_CARL_singlePoint_tZq.append("jprime_Pt")
features_CARL_singlePoint_tZq.append("jPrimeAbsEta")
features_CARL_singlePoint_tZq.append("maxDelPhiLL")
features_CARL_singlePoint_tZq.append("cosThetaStarPolZ")

# features_CARL_singlePoint_tZq.append("dR_bW")
# features_CARL_singlePoint_tZq.append("mHT")
# features_CARL_singlePoint_tZq.append("Mass_3l")
# features_CARL_singlePoint_tZq.append("TopZsystem_M")
# features_CARL_singlePoint_tZq.append("recoLepTop_Pt")
# features_CARL_singlePoint_tZq.append("dR_tClosestJet")

# //--------------------------------------------

features_CARL_singlePoint_ttZ = features_CARL_singlePoint_tZq

# //--------------------------------------------
'''
list_features.append("recoZ_Pt")
list_features.append("recoZ_Eta")
list_features.append("mHT")

list_features.append("mTW")
list_features.append("Mass_3l")
list_features.append("maxDelPhiLL")

list_features.append("lAsymmetry")
list_features.append("jPrimeAbsEta")
list_features.append("maxEtaJet")
list_features.append("maxDeepJet")
list_features.append("njets")
list_features.append("nbjets")

list_features.append("recoLepTop_Pt")
list_features.append("recoLepTop_Eta")
list_features.append("TopZsystem_M")
list_features.append("recoLepTopLep_Pt")
list_features.append("mbjMax")
list_features.append("maxDiJet_Pt")
list_features.append("maxDelRbL")
list_features.append("minDelRbL")
list_features.append("dR_ZlW")
list_features.append("dR_blW")
list_features.append("dR_tClosestJet")
list_features.append("dR_bW")
list_features.append("dEta_jprimeClosestLep")

list_features.append("cosThetaStarPolTop")
list_features.append("cosThetaStarPolZ")
list_features.append("dR_tjprime")
list_features.append("dEta_bjprime")
list_features.append("dR_bjprime")
list_features.append("dR_lWjprime")
list_features.append("dR_Zjprime")
list_features.append("dEta_lWjprime")

list_features.append("dR_tClosestLep")
list_features.append("recoLepTopLep_Eta")
list_features.append("maxDiJet_dPhi")
list_features.append("dR_jprimeClosestLep")
list_features.append("jprime_Pt")
list_features.append("DeepJet_2nd")
list_features.append("maxDeepCSV")
list_features.append("deepCSV_2nd")
list_features.append("recoZ_Phi")
list_features.append("recoZ_M")
list_features.append("maxDiJet_M")
list_features.append("recoLepTop_M")
list_features.append("TopZsystem_Pt")
list_features.append("dR_tZ")
list_features.append("dEta_Zjprime")
list_features.append("dEta_tjprime")
list_features.append("maxDiJet_dEta")
list_features.append("maxDiJet_dR")
list_features.append("recoZLepMinus_Pt")
list_features.append("recoZLepMinus_Eta")
list_features.append("recoZLepMinus_Phi")
list_features.append("recoZLepPlus_Pt")
list_features.append("recoZLepPlus_Eta")
list_features.append("recoZLepPlus_Phi")
list_features.append("recoLepTopLep_Phi")
list_features.append("jprime_Eta")
list_features.append("jprime_Phi")
list_features.append("TopZsystem_Eta")
list_features.append("TopZsystem_Phi")
list_features.append("recoLepTopB_Pt")
list_features.append("recoLepTopB_Eta")
list_features.append("recoLepTopB_Phi")
list_features.append("recoLepTop_Phi")

list_features.append("lep1_pt")
list_features.append("lep2_pt")
list_features.append("lep3_pt");
list_features.append("lep1_eta")
list_features.append("lep2_eta")
list_features.append("lep3_eta")
list_features.append("lep1_phi")
list_features.append("lep2_phi")
list_features.append("lep3_phi")

list_features.append("jet1_pt")
list_features.append("jet2_pt")
list_features.append("jet3_pt")
list_features.append("jet1_eta")
list_features.append("jet2_eta")
list_features.append("jet3_eta")
list_features.append("jet1_phi")
list_features.append("jet2_phi")
list_features.append("jet3_phi")
list_features.append("jet4_pt")
list_features.append("jet4_eta")
list_features.append("jet4_phi")
list_features.append("jet1_DeepCSV")
list_features.append("jet2_DeepCSV")
list_features.append("jet3_DeepCSV")
list_features.append("jet4_DeepCSV")
list_features.append("jet1_DeepJet")
list_features.append("jet2_DeepJet")
list_features.append("jet3_DeepJet")
list_features.append("jet4_DeepJet")
'''
